### ISSUE TITLE
Will there be any further 1.17 updates?

### ISSUE THREAD

**Issue by Noopig** [jsorrell/skyblock#6]
I'm a casual gamer who loves Minecraft. 
Thank you very much for making Skyblock. I'm fascinated by the empty island gameplay.
So, as the title asks, are you going to keep updating?

**Comment by jsorrell** [comment]
Sure. Not sure how long it'll take because it's a major update but hopefully I'll be able to release a 1.17 update by the end of the weekend.

**Comment by Noopig** [comment]
Oh yeah. But please take care of your health, too

**Comment by jsorrell** [comment]
I just released a 1.17 version and took the opportunity to add some new features.

**Comment by Noopig** [comment]
I see. That's great.I am going to translate your Skyblock description in Chinese and send it to Bilibili.

**Comment by Noopig** [comment]
Excuse me。As for the regenerative amethyst buds, I still don't know how to place the lava, Calcite, and Smooth Basalt.I have tried many kinds of encirclements without success.I might need a diagram.

**Comment by jsorrell** [comment]
I'll add a picture soon, but for now you can place 1 lava block, surround the 6 sides of it with calcite, then place a Smooth Basalt against all visible sides of the calcite. 
In two dimensions, it looks like:

```
    B
  B C B
B C L C B
  B C B
    B
```

In 3D, this takes 6 calcite and 12 smooth basalt. It then has a 1/100 chance to convert when the lava receives a random tick. You can test it with `/gamerule randomTickRate 10000` to convert it immediately. Make sure you have the feature enabled by running `/skyblock list renewableBuddingAmethysts`

**Comment by Noopig** [comment]
yes、Thank you for your help.I've tested it successfully.

**Comment by Noopig** [comment]
This is my translation from Bilibili。
https://www.bilibili.com/read/cv12264371
